version: '2.1'

networks:
  lambda-net:

services:

  #######################################
  # Postgres: The database used by Kong
  #######################################
  lambda-database:
    image: postgres:latest
    container_name: lambda-db
    environment:
      POSTGRES_DB: genhub
      POSTGRES_USER: genhub
      POSTGRES_PASSWORD: genhub
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      # creating user
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - lambda-net
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "genhub"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure

  #######################################
  # Example Microservice
  #######################################
  app:
    environment:
      - POSTGRES_IPADDRESS=lambda-db
      - POSTGRES_DB=genhub
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    build: .
    depends_on:
      lambda-database:
        condition: service_healthy
    container_name: genhub-app
    ports:
      - "8000:5000"
    volumes:
      - .:/code
    networks:
      - lambda-net
    restart: on-failure